<Project>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    <Deterministic>true</Deterministic>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
    <VoicePromptVersion>1.4.3</VoicePromptVersion>
    <Version>$(VoicePromptVersion)</Version>
    <Company>tomaskubica</Company>
    <Product>VoicePrompt</Product>
    <Copyright>Copyright (c) Tomáš Kubica</Copyright>
  </PropertyGroup>

</Project>
